"""
Standard ICL task definitions for real-LLM subspace experiments.

Three ID tasks chosen for large vocabulary (300+ distinct pairs each) so that
support and eval pools are genuinely non-overlapping:

  present_to_past   : walk  → walked   (verb morphology, 400+ pairs)
  singular_to_plural: cat   → cats     (noun morphology, 300+ pairs)
  english_to_french : cat   → chat     (translation,     280+ pairs)

Three matched OOD tasks (apply deterministic g to the ID output):
  past_reversed     : walk  → deklaw   (reverse of past tense)
  plural_len        : cat   → 4        (char-count of plural)
  french_reversed   : cat   → tahc     (reverse of French word)
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field
from typing import Callable, Dict, List, Optional, Tuple


# ---------------------------------------------------------------------------
# Raw (x, y) pair data
# ---------------------------------------------------------------------------

# ── 1. Present → Past tense ─────────────────────────────────────────────────
# 400+ English verbs. Only pairs where both forms are unambiguous and
# commonly single-token in LLM tokenisers.

_PRESENT_TO_PAST_RAW: List[Tuple[str, str]] = [
    # ── Regular: simple -ed ─────────────────────────────────────────────────
    ("walk",        "walked"),
    ("talk",        "talked"),
    ("play",        "played"),
    ("watch",       "watched"),
    ("work",        "worked"),
    ("help",        "helped"),
    ("ask",         "asked"),
    ("open",        "opened"),
    ("close",       "closed"),
    ("finish",      "finished"),
    ("start",       "started"),
    ("jump",        "jumped"),
    ("push",        "pushed"),
    ("pull",        "pulled"),
    ("call",        "called"),
    ("add",         "added"),
    ("cook",        "cooked"),
    ("clean",       "cleaned"),
    ("fix",         "fixed"),
    ("pass",        "passed"),
    ("miss",        "missed"),
    ("press",       "pressed"),
    ("dress",       "dressed"),
    ("fill",        "filled"),
    ("kill",        "killed"),
    ("smell",       "smelled"),
    ("yell",        "yelled"),
    ("rain",        "rained"),
    ("want",        "wanted"),
    ("need",        "needed"),
    ("wait",        "waited"),
    ("stay",        "stayed"),
    ("save",        "saved"),
    ("care",        "cared"),
    ("share",       "shared"),
    ("face",        "faced"),
    ("place",       "placed"),
    ("chase",       "chased"),
    ("taste",       "tasted"),
    ("love",        "loved"),
    ("move",        "moved"),
    ("prove",       "proved"),
    ("serve",       "served"),
    ("arrive",      "arrived"),
    ("laugh",       "laughed"),
    ("search",      "searched"),
    ("match",       "matched"),
    ("touch",       "touched"),
    ("march",       "marched"),
    ("burn",        "burned"),
    ("learn",       "learned"),
    ("earn",        "earned"),
    ("return",      "returned"),
    ("turn",        "turned"),
    ("warn",        "warned"),
    ("form",        "formed"),
    ("warm",        "warmed"),
    ("inform",      "informed"),
    ("perform",     "performed"),
    ("follow",      "followed"),
    ("borrow",      "borrowed"),
    ("allow",       "allowed"),
    ("flow",        "flowed"),
    ("glow",        "glowed"),
    ("snow",        "snowed"),
    ("slow",        "slowed"),
    ("row",         "rowed"),
    ("own",         "owned"),
    ("join",        "joined"),
    ("point",       "pointed"),
    ("count",       "counted"),
    ("hunt",        "hunted"),
    ("plant",       "planted"),
    ("print",       "printed"),
    ("rent",        "rented"),
    ("connect",     "connected"),
    ("collect",     "collected"),
    ("protect",     "protected"),
    ("select",      "selected"),
    ("expect",      "expected"),
    ("accept",      "accepted"),
    ("reject",      "rejected"),
    ("reflect",     "reflected"),
    ("direct",      "directed"),
    ("correct",     "corrected"),
    ("affect",      "affected"),
    ("attract",     "attracted"),
    ("attack",      "attacked"),
    ("check",       "checked"),
    ("pick",        "picked"),
    ("kick",        "kicked"),
    ("trick",       "tricked"),
    ("knock",       "knocked"),
    ("lock",        "locked"),
    ("block",       "blocked"),
    ("look",        "looked"),
    ("book",        "booked"),
    ("hook",        "hooked"),
    ("mark",        "marked"),
    ("park",        "parked"),
    ("bark",        "barked"),
    ("answer",      "answered"),
    ("bake",        "baked"),
    ("balance",     "balanced"),
    ("blame",       "blamed"),
    ("breathe",     "breathed"),
    ("brush",       "brushed"),
    ("change",      "changed"),
    ("charge",      "charged"),
    ("climb",       "climbed"),
    ("combine",     "combined"),
    ("compare",     "compared"),
    ("complete",    "completed"),
    ("consider",    "considered"),
    ("contain",     "contained"),
    ("continue",    "continued"),
    ("create",      "created"),
    ("cross",       "crossed"),
    ("dance",       "danced"),
    ("decide",      "decided"),
    ("declare",     "declared"),
    ("design",      "designed"),
    ("develop",     "developed"),
    ("discuss",     "discussed"),
    ("divide",      "divided"),
    ("enjoy",       "enjoyed"),
    ("enter",       "entered"),
    ("escape",      "escaped"),
    ("examine",     "examined"),
    ("exchange",    "exchanged"),
    ("exercise",    "exercised"),
    ("expand",      "expanded"),
    ("explain",     "explained"),
    ("explore",     "explored"),
    ("extend",      "extended"),
    ("force",       "forced"),
    ("gather",      "gathered"),
    ("handle",      "handled"),
    ("happen",      "happened"),
    ("imagine",     "imagined"),
    ("improve",     "improved"),
    ("include",     "included"),
    ("increase",    "increased"),
    ("indicate",    "indicated"),
    ("influence",   "influenced"),
    ("involve",     "involved"),
    ("maintain",    "maintained"),
    ("manage",      "managed"),
    ("measure",     "measured"),
    ("mention",     "mentioned"),
    ("notice",      "noticed"),
    ("observe",     "observed"),
    ("offer",       "offered"),
    ("operate",     "operated"),
    ("order",       "ordered"),
    ("organize",    "organized"),
    ("prepare",     "prepared"),
    ("present",     "presented"),
    ("produce",     "produced"),
    ("provide",     "provided"),
    ("realize",     "realized"),
    ("receive",     "received"),
    ("recognize",   "recognized"),
    ("reduce",      "reduced"),
    ("refuse",      "refused"),
    ("relate",      "related"),
    ("release",     "released"),
    ("remain",      "remained"),
    ("remove",      "removed"),
    ("replace",     "replaced"),
    ("represent",   "represented"),
    ("require",     "required"),
    ("result",      "resulted"),
    ("review",      "reviewed"),
    ("solve",       "solved"),
    ("suggest",     "suggested"),
    ("support",     "supported"),
    ("travel",      "traveled"),
    ("update",      "updated"),
    ("visit",       "visited"),
    ("achieve",     "achieved"),
    ("advance",     "advanced"),
    ("announce",    "announced"),
    ("appear",      "appeared"),
    ("arrange",     "arranged"),
    ("attempt",     "attempted"),
    ("avoid",       "avoided"),
    ("believe",     "believed"),
    ("belong",      "belonged"),
    ("calculate",   "calculated"),
    ("celebrate",   "celebrated"),
    ("challenge",   "challenged"),
    ("communicate", "communicated"),
    ("concentrate", "concentrated"),
    ("confirm",     "confirmed"),
    ("contribute",  "contributed"),
    ("control",     "controlled"),
    ("convert",     "converted"),
    ("convince",    "convinced"),
    ("cover",       "covered"),
    ("damage",      "damaged"),
    ("demonstrate", "demonstrated"),
    ("depend",      "depended"),
    ("describe",    "described"),
    ("determine",   "determined"),
    ("differ",      "differed"),
    ("disagree",    "disagreed"),
    ("discover",    "discovered"),
    ("display",     "displayed"),
    ("distribute",  "distributed"),
    ("download",    "downloaded"),
    ("eliminate",   "eliminated"),
    ("emphasize",   "emphasized"),
    ("encourage",   "encouraged"),
    ("establish",   "established"),
    ("evaluate",    "evaluated"),
    ("exist",       "existed"),
    ("experience",  "experienced"),
    ("express",     "expressed"),
    ("focus",       "focused"),
    ("generate",    "generated"),
    ("identify",    "identified"),
    ("implement",   "implemented"),
    ("install",     "installed"),
    ("interact",    "interacted"),
    ("introduce",   "introduced"),
    ("investigate", "investigated"),
    ("launch",      "launched"),
    ("limit",       "limited"),
    ("list",        "listed"),
    ("load",        "loaded"),
    ("locate",      "located"),
    ("motivate",    "motivated"),
    ("move",        "moved"),
    ("name",        "named"),
    ("need",        "needed"),
    ("negotiate",   "negotiated"),
    ("obtain",      "obtained"),
    ("participate", "participated"),
    ("pass",        "passed"),
    ("perform",     "performed"),
    ("plan",        "planned"),
    ("predict",     "predicted"),
    ("prefer",      "preferred"),
    ("prevent",     "prevented"),
    ("process",     "processed"),
    ("promote",     "promoted"),
    ("propose",     "proposed"),
    ("publish",     "published"),
    ("purchase",    "purchased"),
    ("raise",       "raised"),
    ("reach",       "reached"),
    ("record",      "recorded"),
    ("recover",     "recovered"),
    ("refer",       "referred"),
    ("report",      "reported"),
    ("request",     "requested"),
    ("respond",     "responded"),
    ("restore",     "restored"),
    ("reveal",      "revealed"),
    ("save",        "saved"),
    ("schedule",    "scheduled"),
    ("separate",    "separated"),
    ("share",       "shared"),
    ("show",        "showed"),
    ("signal",      "signaled"),
    ("simplify",    "simplified"),
    ("simulate",    "simulated"),
    ("store",       "stored"),
    ("stretch",     "stretched"),
    ("structure",   "structured"),
    ("transfer",    "transferred"),
    ("transform",   "transformed"),
    ("translate",   "translated"),
    ("understand",  "understood"),  # irregular
    ("upload",      "uploaded"),
    ("use",         "used"),
    ("value",       "valued"),
    ("vary",        "varied"),
    ("waste",       "wasted"),
    # ── Regular: CVC doubling ────────────────────────────────────────────────
    ("stop",        "stopped"),
    ("shop",        "shopped"),
    ("drop",        "dropped"),
    ("grab",        "grabbed"),
    ("slip",        "slipped"),
    ("skip",        "skipped"),
    ("trip",        "tripped"),
    ("flip",        "flipped"),
    ("tip",         "tipped"),
    ("dip",         "dipped"),
    ("pop",         "popped"),
    ("hop",         "hopped"),
    ("tap",         "tapped"),
    ("map",         "mapped"),
    ("cap",         "capped"),
    ("wrap",        "wrapped"),
    ("hug",         "hugged"),
    ("mug",         "mugged"),
    ("tug",         "tugged"),
    ("plug",        "plugged"),
    ("shrug",       "shrugged"),
    ("jam",         "jammed"),
    ("ram",         "rammed"),
    ("slam",        "slammed"),
    ("cram",        "crammed"),
    ("ban",         "banned"),
    ("fan",         "fanned"),
    ("scan",        "scanned"),
    ("tan",         "tanned"),
    ("dim",         "dimmed"),
    ("trim",        "trimmed"),
    ("slim",        "slimmed"),
    ("brim",        "brimmed"),
    ("pin",         "pinned"),
    ("knit",        "knitted"),
    ("pit",         "pitted"),
    ("pet",         "petted"),
    ("wet",         "wetted"),
    ("net",         "netted"),
    ("pat",         "patted"),
    ("bat",         "batted"),
    ("mat",         "matted"),
    ("chat",        "chatted"),
    ("fit",         "fitted"),
    ("gut",         "gutted"),
    ("rut",         "rutted"),
    ("bug",         "bugged"),
    ("drug",        "drugged"),
    ("nod",         "nodded"),
    ("rob",         "robbed"),
    ("sob",         "sobbed"),
    ("jog",         "jogged"),
    ("log",         "logged"),
    ("fog",         "fogged"),
    ("rub",         "rubbed"),
    ("hub",         "hubbed"),
    ("dub",         "dubbed"),
    ("sub",         "subbed"),
    ("zip",         "zipped"),
    ("sip",         "sipped"),
    ("rip",         "ripped"),
    ("hip",         "hipped"),
    ("nip",         "nipped"),
    ("lip",         "lipped"),
    ("bid",         "bided"),
    ("rid",         "ridded"),
    ("wag",         "wagged"),
    ("tag",         "tagged"),
    ("bag",         "bagged"),
    ("nag",         "nagged"),
    ("lag",         "lagged"),
    ("gag",         "gagged"),
    ("sag",         "sagged"),
    ("rag",         "ragged"),
    # ── Regular: -y → -ied ──────────────────────────────────────────────────
    ("carry",       "carried"),
    ("hurry",       "hurried"),
    ("worry",       "worried"),
    ("marry",       "married"),
    ("bury",        "buried"),
    ("copy",        "copied"),
    ("empty",       "emptied"),
    ("study",       "studied"),
    ("reply",       "replied"),
    ("supply",      "supplied"),
    ("apply",       "applied"),
    ("rely",        "relied"),
    ("deny",        "denied"),
    ("fry",         "fried"),
    ("try",         "tried"),
    ("dry",         "dried"),
    ("spy",         "spied"),
    ("cry",         "cried"),
    ("tie",         "tied"),
    ("die",         "died"),
    ("lie",         "lied"),
    ("satisfy",     "satisfied"),
    ("justify",     "justified"),
    ("classify",    "classified"),
    ("clarify",     "clarified"),
    ("qualify",     "qualified"),
    ("notify",      "notified"),
    ("verify",      "verified"),
    ("modify",      "modified"),
    ("multiply",    "multiplied"),
    ("specify",     "specified"),
    ("amplify",     "amplified"),
    ("identify",    "identified"),
    ("signify",     "signified"),
    ("occupy",      "occupied"),
    ("accompany",   "accompanied"),
    ("imply",       "implied"),
    ("comply",      "complied"),
    ("deploy",      "deployed"),
    ("destroy",     "destroyed"),
    ("enjoy",       "enjoyed"),
    # ── Irregular verbs ─────────────────────────────────────────────────────
    ("run",         "ran"),
    ("eat",         "ate"),
    ("go",          "went"),
    ("see",         "saw"),
    ("take",        "took"),
    ("give",        "gave"),
    ("make",        "made"),
    ("come",        "came"),
    ("know",        "knew"),
    ("get",         "got"),
    ("find",        "found"),
    ("think",       "thought"),
    ("buy",         "bought"),
    ("bring",       "brought"),
    ("feel",        "felt"),
    ("lose",        "lost"),
    ("leave",       "left"),
    ("keep",        "kept"),
    ("hold",        "held"),
    ("read",        "read"),
    ("sit",         "sat"),
    ("stand",       "stood"),
    ("send",        "sent"),
    ("spend",       "spent"),
    ("build",       "built"),
    ("drive",       "drove"),
    ("ride",        "rode"),
    ("write",       "wrote"),
    ("bite",        "bit"),
    ("break",       "broke"),
    ("choose",      "chose"),
    ("draw",        "drew"),
    ("drink",       "drank"),
    ("fall",        "fell"),
    ("grow",        "grew"),
    ("hide",        "hid"),
    ("lead",        "led"),
    ("meet",        "met"),
    ("pay",         "paid"),
    ("rise",        "rose"),
    ("sell",        "sold"),
    ("sing",        "sang"),
    ("speak",       "spoke"),
    ("steal",       "stole"),
    ("swim",        "swam"),
    ("teach",       "taught"),
    ("tell",        "told"),
    ("throw",       "threw"),
    ("wear",        "wore"),
    ("cut",         "cut"),
    ("let",         "let"),
    ("put",         "put"),
    ("set",         "set"),
    ("hit",         "hit"),
    ("hurt",        "hurt"),
    ("cost",        "cost"),
    ("shut",        "shut"),
    ("burst",       "burst"),
    ("bleed",       "bled"),
    ("feed",        "fed"),
    ("flee",        "fled"),
    ("sleep",       "slept"),
    ("sweep",       "swept"),
    ("catch",       "caught"),
    ("fight",       "fought"),
    ("seek",        "sought"),
    ("lend",        "lent"),
    ("bend",        "bent"),
    ("creep",       "crept"),
    ("kneel",       "knelt"),
    ("mean",        "meant"),
    ("deal",        "dealt"),
    ("dream",       "dreamt"),
    ("lean",        "leant"),
    ("leap",        "leapt"),
    ("ring",        "rang"),
    ("sink",        "sank"),
    ("shrink",      "shrank"),
    ("begin",       "began"),
    ("spring",      "sprang"),
    ("blow",        "blew"),
    ("freeze",      "froze"),
    ("wake",        "woke"),
    ("shake",       "shook"),
    ("swear",       "swore"),
    ("tear",        "tore"),
    ("bear",        "bore"),
    ("forget",      "forgot"),
    ("forgive",     "forgave"),
    ("shoot",       "shot"),
    ("shine",       "shone"),
    ("slide",       "slid"),
    ("split",       "split"),
    ("spread",      "spread"),
    ("strike",      "struck"),
    ("swing",       "swung"),
    ("wind",        "wound"),
    ("bind",        "bound"),
    ("grind",       "ground"),
    ("have",        "had"),
    ("hear",        "heard"),
    ("lay",         "laid"),
    ("say",         "said"),
    ("win",         "won"),
    ("fly",         "flew"),
    ("hang",        "hung"),
    ("light",       "lit"),
    ("sting",       "stung"),
    ("stink",       "stank"),
    ("stride",      "strode"),
    ("string",      "strung"),
    ("arise",       "arose"),
    ("overcome",    "overcame"),
    ("undergo",     "underwent"),
    ("withdraw",    "withdrew"),
    ("withstand",   "withstood"),
    ("forbid",      "forbade"),
    ("mistake",     "mistook"),
    ("upset",       "upset"),
    ("input",       "input"),
    ("output",      "output"),
    ("forecast",    "forecast"),
    ("broadcast",   "broadcast"),
    ("cling",       "clung"),
    ("dig",         "dug"),
    ("do",          "did"),
    ("spit",        "spat"),
    ("spin",        "spun"),
    ("sling",       "slung"),
    ("fling",       "flung"),
    ("wring",       "wrung"),
    ("shrink",      "shrank"),
    ("strive",      "strove"),
]

# De-duplicate on input word (first occurrence wins)
_seen_past: set = set()
_PRESENT_TO_PAST: List[Tuple[str, str]] = []
for _p in _PRESENT_TO_PAST_RAW:
    if _p[0] not in _seen_past:
        _seen_past.add(_p[0])
        _PRESENT_TO_PAST.append(_p)


# ── 2. Singular → Plural ────────────────────────────────────────────────────
# 300+ English nouns covering regular and irregular forms.

_SINGULAR_TO_PLURAL_RAW: List[Tuple[str, str]] = [
    # ── Regular -s ──────────────────────────────────────────────────────────
    ("cat",           "cats"),
    ("dog",           "dogs"),
    ("book",          "books"),
    ("table",         "tables"),
    ("chair",         "chairs"),
    ("door",          "doors"),
    ("window",        "windows"),
    ("car",           "cars"),
    ("tree",          "trees"),
    ("flower",        "flowers"),
    ("bird",          "birds"),
    ("star",          "stars"),
    ("street",        "streets"),
    ("park",          "parks"),
    ("hand",          "hands"),
    ("eye",           "eyes"),
    ("arm",           "arms"),
    ("leg",           "legs"),
    ("head",          "heads"),
    ("heart",         "hearts"),
    ("room",          "rooms"),
    ("wall",          "walls"),
    ("floor",         "floors"),
    ("bed",           "beds"),
    ("cup",           "cups"),
    ("plate",         "plates"),
    ("fork",          "forks"),
    ("spoon",         "spoons"),
    ("shoe",          "shoes"),
    ("bag",           "bags"),
    ("hat",           "hats"),
    ("coat",          "coats"),
    ("shirt",         "shirts"),
    ("sock",          "socks"),
    ("ring",          "rings"),
    ("key",           "keys"),
    ("coin",          "coins"),
    ("map",           "maps"),
    ("lamp",          "lamps"),
    ("clock",         "clocks"),
    ("phone",         "phones"),
    ("ball",          "balls"),
    ("rope",          "ropes"),
    ("bowl",          "bowls"),
    ("pot",           "pots"),
    ("pan",           "pans"),
    ("jar",           "jars"),
    ("cake",          "cakes"),
    ("grape",         "grapes"),
    ("apple",         "apples"),
    ("bean",          "beans"),
    ("seed",          "seeds"),
    ("root",          "roots"),
    ("cloud",         "clouds"),
    ("wave",          "waves"),
    ("lake",          "lakes"),
    ("hill",          "hills"),
    ("train",         "trains"),
    ("plane",         "planes"),
    ("boat",          "boats"),
    ("ship",          "ships"),
    ("road",          "roads"),
    ("path",          "paths"),
    ("farm",          "farms"),
    ("field",         "fields"),
    ("stone",         "stones"),
    ("rock",          "rocks"),
    ("sand",          "sands"),
    ("shell",         "shells"),
    ("animal",        "animals"),
    ("answer",        "answers"),
    ("apartment",     "apartments"),
    ("airport",       "airports"),
    ("article",       "articles"),
    ("beach",         "beaches"),
    ("benefit",       "benefits"),
    ("birthday",      "birthdays"),
    ("button",        "buttons"),
    ("camera",        "cameras"),
    ("college",       "colleges"),
    ("comment",       "comments"),
    ("computer",      "computers"),
    ("corner",        "corners"),
    ("customer",      "customers"),
    ("debate",        "debates"),
    ("design",        "designs"),
    ("detail",        "details"),
    ("direction",     "directions"),
    ("disease",       "diseases"),
    ("distance",      "distances"),
    ("document",      "documents"),
    ("effect",        "effects"),
    ("effort",        "efforts"),
    ("element",       "elements"),
    ("employee",      "employees"),
    ("environment",   "environments"),
    ("event",         "events"),
    ("example",       "examples"),
    ("experiment",    "experiments"),
    ("fact",          "facts"),
    ("feature",       "features"),
    ("feeling",       "feelings"),
    ("festival",      "festivals"),
    ("figure",        "figures"),
    ("function",      "functions"),
    ("goal",          "goals"),
    ("group",         "groups"),
    ("hospital",      "hospitals"),
    ("hotel",         "hotels"),
    ("idea",          "ideas"),
    ("image",         "images"),
    ("island",        "islands"),
    ("journey",       "journeys"),
    ("leader",        "leaders"),
    ("level",         "levels"),
    ("location",      "locations"),
    ("machine",       "machines"),
    ("meeting",       "meetings"),
    ("message",       "messages"),
    ("method",        "methods"),
    ("minute",        "minutes"),
    ("mistake",       "mistakes"),
    ("model",         "models"),
    ("moment",        "moments"),
    ("museum",        "museums"),
    ("nation",        "nations"),
    ("network",       "networks"),
    ("number",        "numbers"),
    ("object",        "objects"),
    ("ocean",         "oceans"),
    ("owner",         "owners"),
    ("package",       "packages"),
    ("partner",       "partners"),
    ("patient",       "patients"),
    ("period",        "periods"),
    ("picture",       "pictures"),
    ("piece",         "pieces"),
    ("planet",        "planets"),
    ("point",         "points"),
    ("problem",       "problems"),
    ("product",       "products"),
    ("project",       "projects"),
    ("purpose",       "purposes"),
    ("record",        "records"),
    ("report",        "reports"),
    ("request",       "requests"),
    ("resource",      "resources"),
    ("result",        "results"),
    ("role",          "roles"),
    ("rule",          "rules"),
    ("scene",         "scenes"),
    ("section",       "sections"),
    ("service",       "services"),
    ("skill",         "skills"),
    ("solution",      "solutions"),
    ("source",        "sources"),
    ("statement",     "statements"),
    ("step",          "steps"),
    ("structure",     "structures"),
    ("student",       "students"),
    ("subject",       "subjects"),
    ("suggestion",    "suggestions"),
    ("survey",        "surveys"),
    ("system",        "systems"),
    ("task",          "tasks"),
    ("team",          "teams"),
    ("technique",     "techniques"),
    ("topic",         "topics"),
    ("tradition",     "traditions"),
    ("value",         "values"),
    ("version",       "versions"),
    ("village",       "villages"),
    ("volume",        "volumes"),
    ("weapon",        "weapons"),
    ("account",       "accounts"),
    ("agreement",     "agreements"),
    ("challenge",     "challenges"),
    ("character",     "characters"),
    ("component",     "components"),
    ("concept",       "concepts"),
    ("connection",    "connections"),
    ("consequence",   "consequences"),
    ("context",       "contexts"),
    ("contract",      "contracts"),
    ("contribution",  "contributions"),
    ("conversation",  "conversations"),
    ("decision",      "decisions"),
    ("department",    "departments"),
    ("development",   "developments"),
    ("difference",    "differences"),
    ("discovery",     "discoveries"),
    ("door",          "doors"),
    ("equipment",     "equipment"),
    ("experience",    "experiences"),
    ("explanation",   "explanations"),
    ("flower",        "flowers"),
    ("government",    "governments"),
    ("idea",          "ideas"),
    ("individual",    "individuals"),
    ("institution",   "institutions"),
    ("interaction",   "interactions"),
    ("investigation", "investigations"),
    ("issue",         "issues"),
    ("job",           "jobs"),
    ("lack",          "lacks"),
    ("language",      "languages"),
    ("letter",        "letters"),
    ("link",          "links"),
    ("list",          "lists"),
    ("literature",    "literatures"),
    ("magazine",      "magazines"),
    ("material",      "materials"),
    ("mountain",      "mountains"),
    ("movement",      "movements"),
    ("name",          "names"),
    ("option",        "options"),
    ("organization",  "organizations"),
    ("paragraph",     "paragraphs"),
    ("phone",         "phones"),
    ("plan",          "plans"),
    ("population",    "populations"),
    ("position",      "positions"),
    ("process",       "processes"),
    ("profession",    "professions"),
    ("program",       "programs"),
    ("publication",   "publications"),
    ("quality",       "qualities"),
    ("question",      "questions"),
    ("reason",        "reasons"),
    ("relationship",  "relationships"),
    ("restaurant",    "restaurants"),
    ("river",         "rivers"),
    ("sentence",      "sentences"),
    ("situation",     "situations"),
    ("solution",      "solutions"),
    ("sound",         "sounds"),
    ("space",         "spaces"),
    ("sport",         "sports"),
    ("statement",     "statements"),
    ("store",         "stores"),
    ("student",       "students"),
    ("thought",       "thoughts"),
    ("tool",          "tools"),
    ("town",          "towns"),
    ("type",          "types"),
    ("view",          "views"),
    ("word",          "words"),
    ("year",          "years"),
    # ── Regular -es (sibilants) ──────────────────────────────────────────────
    ("bus",           "buses"),
    ("glass",         "glasses"),
    ("class",         "classes"),
    ("dress",         "dresses"),
    ("guess",         "guesses"),
    ("kiss",          "kisses"),
    ("boss",          "bosses"),
    ("tax",           "taxes"),
    ("fox",           "foxes"),
    ("mix",           "mixes"),
    ("box",           "boxes"),
    ("match",         "matches"),
    ("watch",         "watches"),
    ("batch",         "batches"),
    ("patch",         "patches"),
    ("ranch",         "ranches"),
    ("branch",        "branches"),
    ("church",        "churches"),
    ("arch",          "arches"),
    ("torch",         "torches"),
    ("bench",         "benches"),
    ("inch",          "inches"),
    ("bunch",         "bunches"),
    ("lunch",         "lunches"),
    ("brush",         "brushes"),
    ("dish",          "dishes"),
    ("wish",          "wishes"),
    ("flash",         "flashes"),
    ("crash",         "crashes"),
    # ── Regular -ies (consonant + y) ────────────────────────────────────────
    ("city",          "cities"),
    ("baby",          "babies"),
    ("lady",          "ladies"),
    ("party",         "parties"),
    ("story",         "stories"),
    ("body",          "bodies"),
    ("copy",          "copies"),
    ("country",       "countries"),
    ("family",        "families"),
    ("army",          "armies"),
    ("enemy",         "enemies"),
    ("penny",         "pennies"),
    ("berry",         "berries"),
    ("cherry",        "cherries"),
    ("ferry",         "ferries"),
    ("library",       "libraries"),
    ("factory",       "factories"),
    ("category",      "categories"),
    ("dictionary",    "dictionaries"),
    ("opportunity",   "opportunities"),
    ("policy",        "policies"),
    ("strategy",      "strategies"),
    ("theory",        "theories"),
    ("variety",       "varieties"),
    ("university",    "universities"),
    # ── Regular -ves (f/fe → ves) ────────────────────────────────────────────
    ("half",          "halves"),
    ("loaf",          "loaves"),
    ("calf",          "calves"),
    ("wolf",          "wolves"),
    ("shelf",         "shelves"),
    ("elf",           "elves"),
    ("self",          "selves"),
    ("life",          "lives"),
    ("wife",          "wives"),
    ("thief",         "thieves"),
    ("leaf",          "leaves"),
    ("scarf",         "scarves"),
    ("knife",         "knives"),
    # ── Irregular ───────────────────────────────────────────────────────────
    ("tooth",         "teeth"),
    ("foot",          "feet"),
    ("goose",         "geese"),
    ("mouse",         "mice"),
    ("child",         "children"),
    ("man",           "men"),
    ("woman",         "women"),
    ("person",        "people"),
    ("ox",            "oxen"),
    ("sheep",         "sheep"),
    ("deer",          "deer"),
    ("criterion",     "criteria"),
    ("medium",        "media"),
    ("datum",         "data"),
    ("stimulus",      "stimuli"),
    ("cactus",        "cacti"),
    ("fungus",        "fungi"),
    ("alumnus",       "alumni"),
    ("nucleus",       "nuclei"),
    ("syllabus",      "syllabi"),
    ("analysis",      "analyses"),
    ("basis",         "bases"),
    ("crisis",        "crises"),
    ("thesis",        "theses"),
    ("axis",          "axes"),
    ("appendix",      "appendices"),
    ("index",         "indices"),
    ("matrix",        "matrices"),
    ("vertex",        "vertices"),
]

_seen_plural: set = set()
_SINGULAR_TO_PLURAL: List[Tuple[str, str]] = []
for _p in _SINGULAR_TO_PLURAL_RAW:
    if _p[0] not in _seen_plural:
        _seen_plural.add(_p[0])
        _SINGULAR_TO_PLURAL.append(_p)


# ── 3. English → French ─────────────────────────────────────────────────────
# 280+ common words. Prefer single-token French forms.

_ENGLISH_TO_FRENCH_RAW: List[Tuple[str, str]] = [
    # Animals
    ("cat",          "chat"),
    ("dog",          "chien"),
    ("horse",        "cheval"),
    ("bird",         "oiseau"),
    ("fish",         "poisson"),
    ("mouse",        "souris"),
    ("rabbit",       "lapin"),
    ("bear",         "ours"),
    ("lion",         "lion"),
    ("tiger",        "tigre"),
    ("wolf",         "loup"),
    ("fox",          "renard"),
    ("duck",         "canard"),
    ("owl",          "hibou"),
    ("eagle",        "aigle"),
    ("snake",        "serpent"),
    ("frog",         "grenouille"),
    ("bee",          "abeille"),
    ("butterfly",    "papillon"),
    ("cow",          "vache"),
    ("pig",          "cochon"),
    ("sheep",        "mouton"),
    ("goat",         "chèvre"),
    ("elephant",     "éléphant"),
    ("monkey",       "singe"),
    ("whale",        "baleine"),
    ("shark",        "requin"),
    ("dove",         "colombe"),
    ("ant",          "fourmi"),
    ("fly",          "mouche"),
    ("spider",       "araignée"),
    ("deer",         "cerf"),
    ("camel",        "chameau"),
    ("parrot",       "perroquet"),
    ("penguin",      "pingouin"),
    ("crocodile",    "crocodile"),
    # Food
    ("bread",        "pain"),
    ("water",        "eau"),
    ("wine",         "vin"),
    ("milk",         "lait"),
    ("cheese",       "fromage"),
    ("butter",       "beurre"),
    ("egg",          "oeuf"),
    ("rice",         "riz"),
    ("sugar",        "sucre"),
    ("salt",         "sel"),
    ("apple",        "pomme"),
    ("grape",        "raisin"),
    ("orange",       "orange"),
    ("lemon",        "citron"),
    ("banana",       "banane"),
    ("strawberry",   "fraise"),
    ("cherry",       "cerise"),
    ("peach",        "pêche"),
    ("pear",         "poire"),
    ("tomato",       "tomate"),
    ("carrot",       "carotte"),
    ("onion",        "oignon"),
    ("garlic",       "ail"),
    ("mushroom",     "champignon"),
    ("meat",         "viande"),
    ("chicken",      "poulet"),
    ("soup",         "soupe"),
    ("coffee",       "café"),
    ("tea",          "thé"),
    ("beer",         "bière"),
    ("chocolate",    "chocolat"),
    ("honey",        "miel"),
    ("pepper",       "poivre"),
    ("oil",          "huile"),
    ("salad",        "salade"),
    ("pasta",        "pâtes"),
    ("cake",         "gâteau"),
    ("cookie",       "biscuit"),
    ("jam",          "confiture"),
    ("cream",        "crème"),
    ("yogurt",       "yaourt"),
    # Nature
    ("sun",          "soleil"),
    ("moon",         "lune"),
    ("star",         "étoile"),
    ("sky",          "ciel"),
    ("cloud",        "nuage"),
    ("rain",         "pluie"),
    ("snow",         "neige"),
    ("wind",         "vent"),
    ("fire",         "feu"),
    ("earth",        "terre"),
    ("sea",          "mer"),
    ("river",        "rivière"),
    ("lake",         "lac"),
    ("mountain",     "montagne"),
    ("forest",       "forêt"),
    ("tree",         "arbre"),
    ("flower",       "fleur"),
    ("grass",        "herbe"),
    ("stone",        "pierre"),
    ("sand",         "sable"),
    ("ice",          "glace"),
    ("wave",         "vague"),
    ("island",       "île"),
    ("desert",       "désert"),
    ("valley",       "vallée"),
    ("storm",        "tempête"),
    ("thunder",      "tonnerre"),
    ("lightning",    "éclair"),
    ("fog",          "brouillard"),
    ("frost",        "gel"),
    ("soil",         "sol"),
    ("rock",         "roche"),
    ("cave",         "grotte"),
    ("swamp",        "marais"),
    ("beach",        "plage"),
    # Body
    ("head",         "tête"),
    ("eye",          "oeil"),
    ("ear",          "oreille"),
    ("nose",         "nez"),
    ("mouth",        "bouche"),
    ("hand",         "main"),
    ("foot",         "pied"),
    ("arm",          "bras"),
    ("leg",          "jambe"),
    ("finger",       "doigt"),
    ("heart",        "coeur"),
    ("back",         "dos"),
    ("shoulder",     "épaule"),
    ("knee",         "genou"),
    ("neck",         "cou"),
    ("face",         "visage"),
    ("lip",          "lèvre"),
    ("tooth",        "dent"),
    ("skin",         "peau"),
    ("brain",        "cerveau"),
    ("blood",        "sang"),
    ("bone",         "os"),
    ("tongue",       "langue"),
    ("chest",        "poitrine"),
    ("stomach",      "estomac"),
    ("throat",       "gorge"),
    # House & objects
    ("house",        "maison"),
    ("door",         "porte"),
    ("window",       "fenêtre"),
    ("table",        "table"),
    ("chair",        "chaise"),
    ("bed",          "lit"),
    ("book",         "livre"),
    ("car",          "voiture"),
    ("road",         "route"),
    ("school",       "école"),
    ("garden",       "jardin"),
    ("kitchen",      "cuisine"),
    ("glass",        "verre"),
    ("paper",        "papier"),
    ("music",        "musique"),
    ("city",         "ville"),
    ("market",       "marché"),
    ("church",       "église"),
    ("bridge",       "pont"),
    ("clock",        "horloge"),
    ("lamp",         "lampe"),
    ("mirror",       "miroir"),
    ("carpet",       "tapis"),
    ("blanket",      "couverture"),
    ("pillow",       "oreiller"),
    ("cup",          "tasse"),
    ("plate",        "assiette"),
    ("fork",         "fourchette"),
    ("spoon",        "cuillère"),
    ("knife",        "couteau"),
    ("key",          "clé"),
    ("box",          "boîte"),
    ("bag",          "sac"),
    ("hat",          "chapeau"),
    ("coat",         "manteau"),
    ("shirt",        "chemise"),
    ("shoe",         "chaussure"),
    ("ring",         "bague"),
    ("pen",          "stylo"),
    ("pencil",       "crayon"),
    ("letter",       "lettre"),
    ("gift",         "cadeau"),
    ("phone",        "téléphone"),
    # Clothing
    ("dress",        "robe"),
    ("sock",         "chaussette"),
    ("glove",        "gant"),
    ("scarf",        "écharpe"),
    ("belt",         "ceinture"),
    ("jacket",       "veste"),
    ("boot",         "botte"),
    ("skirt",        "jupe"),
    ("tie",          "cravate"),
    ("pocket",       "poche"),
    ("button",       "bouton"),
    ("sleeve",       "manche"),
    ("collar",       "col"),
    # Colours
    ("red",          "rouge"),
    ("blue",         "bleu"),
    ("green",        "vert"),
    ("yellow",       "jaune"),
    ("white",        "blanc"),
    ("black",        "noir"),
    ("grey",         "gris"),
    ("pink",         "rose"),
    ("purple",       "violet"),
    ("brown",        "brun"),
    # Abstract / other
    ("name",         "nom"),
    ("time",         "temps"),
    ("day",          "jour"),
    ("night",        "nuit"),
    ("week",         "semaine"),
    ("month",        "mois"),
    ("year",         "année"),
    ("life",         "vie"),
    ("love",         "amour"),
    ("friend",       "ami"),
    ("family",       "famille"),
    ("child",        "enfant"),
    ("man",          "homme"),
    ("woman",        "femme"),
    ("work",         "travail"),
    ("money",        "argent"),
    ("game",         "jeu"),
    ("dream",        "rêve"),
    ("truth",        "vérité"),
    ("world",        "monde"),
    ("country",      "pays"),
    ("language",     "langue"),
    ("word",         "mot"),
    ("voice",        "voix"),
    ("song",         "chanson"),
    ("war",          "guerre"),
    ("peace",        "paix"),
    ("freedom",      "liberté"),
    ("hope",         "espoir"),
    ("number",       "nombre"),
    ("colour",       "couleur"),
    ("light",        "lumière"),
    ("shadow",       "ombre"),
    ("heat",         "chaleur"),
    ("cold",         "froid"),
    ("noise",        "bruit"),
    ("silence",      "silence"),
    ("danger",       "danger"),
    ("chance",       "chance"),
    ("memory",       "mémoire"),
    ("knowledge",    "connaissance"),
    ("power",        "pouvoir"),
    ("strength",     "force"),
    ("speed",        "vitesse"),
    ("size",         "taille"),
    ("weight",       "poids"),
    ("distance",     "distance"),
    ("direction",    "direction"),
    ("reason",       "raison"),
    # Professions
    ("doctor",       "médecin"),
    ("teacher",      "professeur"),
    ("lawyer",       "avocat"),
    ("engineer",     "ingénieur"),
    ("artist",       "artiste"),
    ("farmer",       "fermier"),
    ("soldier",      "soldat"),
    ("pilot",        "pilote"),
    ("writer",       "écrivain"),
    ("painter",      "peintre"),
    ("dancer",       "danseur"),
    ("singer",       "chanteur"),
    ("actor",        "acteur"),
    ("student",      "étudiant"),
    ("manager",      "directeur"),
    # Transport
    ("bicycle",      "vélo"),
    ("taxi",         "taxi"),
    ("truck",        "camion"),
    ("motorcycle",   "moto"),
    ("boat",         "bateau"),
    ("train",        "train"),
    ("plane",        "avion"),
    ("bus",          "bus"),
    # Emotions
    ("happiness",    "bonheur"),
    ("sadness",      "tristesse"),
    ("fear",         "peur"),
    ("anger",        "colère"),
    ("joy",          "joie"),
    ("surprise",     "surprise"),
    ("shame",        "honte"),
    ("pride",        "fierté"),
    ("jealousy",     "jalousie"),
]

_seen_fr: set = set()
_ENGLISH_TO_FRENCH: List[Tuple[str, str]] = []
for _p in _ENGLISH_TO_FRENCH_RAW:
    if _p[0] not in _seen_fr:
        _seen_fr.add(_p[0])
        _ENGLISH_TO_FRENCH.append(_p)


# ---------------------------------------------------------------------------
# OOD transforms  g : str -> str
# ---------------------------------------------------------------------------

def _reverse(y: str) -> str:
    """Reverse the string character by character."""
    return y[::-1]


def _len_str(y: str) -> str:
    """Return the number of non-space characters as a string."""
    return str(len(y.replace(" ", "")))


# Maps OOD task name → (base_id_task, g_func, g_description)
OOD_SPEC: Dict[str, Tuple[str, Callable[[str], str], str]] = {
    # reverse of the past-tense form:  "walked" → "deklaw"
    "past_reversed":   ("present_to_past",    _reverse,  "reversed past tense"),
    # char count of plural:            "cats"   → "4"
    "plural_len":      ("singular_to_plural", _len_str,  "length of plural"),
    # reverse of French word:          "chat"   → "tahc"
    "french_reversed": ("english_to_french",  _reverse,  "reversed French word"),
}


# ---------------------------------------------------------------------------
# Task dataset class
# ---------------------------------------------------------------------------

@dataclass
class ICLTask:
    """A single ICL task with (x, y) demonstration pairs."""

    name: str
    pairs: List[Tuple[str, str]]
    separator: str = ": "
    ood_transform: Optional[Callable[[str], str]] = None
    ood_name: Optional[str] = None

    def __post_init__(self):
        if len(self.pairs) < 10:
            raise ValueError(f"Task {self.name!r} needs ≥ 10 pairs, got {len(self.pairs)}")

    def format_demo(self, x: str, y: str) -> str:
        return f"{x}{self.separator}{y}"

    def format_query(self, x: str) -> str:
        return f"{x}{self.separator}"

    def build_prompt(self, demo_pairs: List[Tuple[str, str]], query_x: str) -> str:
        """Build ICL prompt ending with '<query_x>: ' (no trailing newline)."""
        lines = [self.format_demo(x, y) for x, y in demo_pairs]
        lines.append(self.format_query(query_x))
        return "\n".join(lines)

    def build_ood_prompt(self, demo_pairs: List[Tuple[str, str]], query_x: str) -> str:
        if self.ood_transform is None:
            raise ValueError(f"Task {self.name!r} has no OOD transform set.")
        return self.build_prompt([(x, self.ood_transform(y)) for x, y in demo_pairs], query_x)

    def support_eval_split(
        self,
        n_support: int = 100,
        seed: int = 0,
    ) -> Tuple[List[Tuple[str, str]], List[Tuple[str, str]]]:
        """Non-overlapping split into support and eval pools."""
        rng = random.Random(seed)
        shuffled = list(self.pairs)
        rng.shuffle(shuffled)
        if n_support >= len(shuffled):
            raise ValueError(
                f"n_support={n_support} ≥ len(pairs)={len(shuffled)} for task {self.name!r}"
            )
        return shuffled[:n_support], shuffled[n_support:]

    def sample_prompts(
        self,
        pool: List[Tuple[str, str]],
        n_prompts: int,
        n_shots: int,
        seed: int = 0,
        ood: bool = False,
    ) -> List[str]:
        """Sample n_prompts ICL prompts, each with n_shots demos + 1 query."""
        if len(pool) < n_shots + 1:
            raise ValueError(
                f"pool size {len(pool)} < n_shots+1={n_shots + 1} for task {self.name!r}"
            )
        rng = random.Random(seed)
        prompts = []
        for _ in range(n_prompts):
            sample = rng.sample(pool, n_shots + 1)
            demos, query = sample[:n_shots], sample[n_shots]
            query_x = query[0]
            prompt = self.build_ood_prompt(demos, query_x) if ood else self.build_prompt(demos, query_x)
            prompts.append(prompt)
        return prompts


# ---------------------------------------------------------------------------
# Task registry
# ---------------------------------------------------------------------------

def make_id_tasks() -> Dict[str, ICLTask]:
    """Return the three ID tasks."""
    return {
        "present_to_past":    ICLTask(name="present_to_past",    pairs=_PRESENT_TO_PAST),
        "singular_to_plural": ICLTask(name="singular_to_plural", pairs=_SINGULAR_TO_PLURAL),
        "english_to_french":  ICLTask(name="english_to_french",  pairs=_ENGLISH_TO_FRENCH),
    }


def make_ood_tasks() -> Dict[str, ICLTask]:
    """Return the three OOD tasks (one per ID task)."""
    id_tasks = make_id_tasks()
    return {
        ood_name: ICLTask(
            name=ood_name,
            pairs=id_tasks[parent_id_name].pairs,
            ood_transform=g_func,
            ood_name=g_desc,
        )
        for ood_name, (parent_id_name, g_func, g_desc) in OOD_SPEC.items()
    }


# ---------------------------------------------------------------------------
# Experiment prompt builder
# ---------------------------------------------------------------------------

@dataclass
class ExperimentPrompts:
    """All prompts for one run of the subspace analysis experiment."""

    support_prompts:  Dict[str, List[str]]
    id_eval_prompts:  Dict[str, List[str]]
    ood_eval_prompts: Dict[str, List[str]]
    task_names:       List[str]
    ood_task_names:   List[str]


def build_experiment_prompts(
    n_support_prompts: int = 50,
    n_eval_prompts:    int = 60,
    n_shots:           int = 10,
    n_support_pairs:   int = 100,
    seed:              int = 0,
) -> ExperimentPrompts:
    """Build support + ID-eval + OOD-eval prompts for the subspace experiment.

    Parameters
    ----------
    n_support_prompts : int
        Prompts per ID task averaged to form task vector τ_k.
    n_eval_prompts : int
        Held-out prompts per task for R² / λ evaluation.
    n_shots : int
        In-context demonstrations per prompt.
    n_support_pairs : int
        Pairs in the support pool (rest go to eval pool).
        With 300+ pairs per task, n_support_pairs=100 leaves 200+ for eval.
    seed : int
    """
    id_tasks  = make_id_tasks()
    ood_tasks = make_ood_tasks()

    # Pre-compute all (support_pool, eval_pool) splits once, keyed by task name.
    # Splitting once and reusing guarantees the same partition is used everywhere.
    splits: Dict[str, Tuple[List[Tuple[str, str]], List[Tuple[str, str]]]] = {
        name: task.support_eval_split(n_support=n_support_pairs, seed=seed)
        for name, task in id_tasks.items()
    }

    # ── Strict non-overlap assertion ─────────────────────────────────────────
    # Verify support_pool ∩ eval_pool = ∅ for every task.
    # This is guaranteed by the slice partition in support_eval_split, but we
    # assert explicitly so any future refactoring that breaks it is caught.
    for name, (sup, ev) in splits.items():
        sup_set = set(x for x, _ in sup)
        ev_set  = set(x for x, _ in ev)
        overlap = sup_set & ev_set
        if overlap:
            raise AssertionError(
                f"Task {name!r}: {len(overlap)} input(s) appear in BOTH support "
                f"and eval pools — strict non-overlap violated.\n"
                f"  Overlapping inputs: {sorted(overlap)[:5]} …"
            )
    # ─────────────────────────────────────────────────────────────────────────

    support_prompts:  Dict[str, List[str]] = {}
    id_eval_prompts:  Dict[str, List[str]] = {}

    for name, task in id_tasks.items():
        support_pool, eval_pool = splits[name]
        support_prompts[name] = task.sample_prompts(support_pool, n_support_prompts, n_shots, seed=seed)
        id_eval_prompts[name] = task.sample_prompts(eval_pool,    n_eval_prompts,    n_shots, seed=seed + 1)

    ood_eval_prompts: Dict[str, List[str]] = {}
    for ood_name, ood_task in ood_tasks.items():
        parent_id_name = OOD_SPEC[ood_name][0]
        _, eval_pool = splits[parent_id_name]   # reuse the same split — no re-shuffle
        ood_eval_prompts[ood_name] = ood_task.sample_prompts(
            eval_pool, n_eval_prompts, n_shots, seed=seed + 2, ood=True
        )

    return ExperimentPrompts(
        support_prompts=support_prompts,
        id_eval_prompts=id_eval_prompts,
        ood_eval_prompts=ood_eval_prompts,
        task_names=list(id_tasks.keys()),
        ood_task_names=list(ood_tasks.keys()),
    )
